from enum import Enum
from typing import List, Optional
from pydantic import BaseModel, Field

class SeverityLevel(str, Enum):
    """Enumeration for vulnerability severity levels."""
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    INFO = "INFO"

class Vulnerability(BaseModel):
    """
    Represents a single security vulnerability found in the IaC code.
    The LLM will be forced to populate these exact fields.
    """
    rule_id: str = Field(
        ..., 
        description="A unique identifier for the vulnerability rule (e.g., IAM-001)."
    )
    resource_name: str = Field(
        ..., 
        description="The name of the Terraform resource affected."
    )
    severity: SeverityLevel = Field(
        ..., 
        description="The severity level of the vulnerability."
    )
    description: str = Field(
        ..., 
        description="A clear, concise explanation of the security issue."
    )
    remediation: str = Field(
        ..., 
        description="Actionable steps to fix the vulnerability."
    )
    line_number: Optional[int] = Field(
        None, 
        description="The approximate line number where the issue occurs, if detectable."
    )

class SecurityReport(BaseModel):
    """
    The final structured report generated by the LLM.
    """
    file_name: str = Field(
        ..., 
        description="The name of the analyzed Terraform file."
    )
    total_issues_found: int = Field(
        ..., 
        description="Total number of vulnerabilities identified."
    )
    vulnerabilities: List[Vulnerability] = Field(
        ..., 
        description="List of all detected vulnerabilities."
    )